field: a8866897-a11c-4d44-bbca-2997e4ab9b0c
fieldLayouts:
  0156c9c1-c806-47c8-9a86-6870cb2ef14b:
    tabs:
      -
        elements:
          -
            fieldUid: 501e23ea-8ec1-4193-97aa-b78cba99f3ac
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  501e23ea-8ec1-4193-97aa-b78cba99f3ac:
    contentColumnType: text
    fieldGroup: null
    handle: copyright
    instructions: ''
    name: Copyright
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: copyright
name: Copyright
sortOrder: 1
