field: acbc0bba-242f-40cf-bdd1-a6417f6eeaa9
fieldLayouts:
  4ae26920-742a-4e6d-9b02-e938c7cc4a42:
    tabs:
      -
        elements:
          -
            fieldUid: 0c1c29aa-3066-417e-a569-3b8ad4b2ccbf
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 213c5cea-e8c3-48a5-9501-d506030864dd
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7fb40023-ad56-4c67-bc65-9353674d5c1b
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 29a1fb65-d50c-4f48-8297-164038ba941a
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0c1c29aa-3066-417e-a569-3b8ad4b2ccbf:
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: ''
    name: Quote
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  7fb40023-ad56-4c67-bc65-9353674d5c1b:
    contentColumnType: text
    fieldGroup: null
    handle: citation
    instructions: ''
    name: Citation
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  29a1fb65-d50c-4f48-8297-164038ba941a:
    contentColumnType: string(255)
    fieldGroup: null
    handle: citationLink
    instructions: 'Add a link if relevant to the source'
    name: 'Citation link'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Url
  213c5cea-e8c3-48a5-9501-d506030864dd:
    contentColumnType: text
    fieldGroup: null
    handle: citationIntro
    instructions: ''
    name: 'Citation intro'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: quote
name: Quote
sortOrder: 4
