field: 9abbaee7-cb0e-4e11-b58f-88ba10242b3b
fieldLayouts:
  e9526af7-5d0b-41a5-afbd-c535148b724e:
    tabs:
      -
        elements:
          -
            fieldUid: 1f3e832f-50bb-4ce8-b8c1-bf85468f60ab
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 67d32d80-82f8-48c3-adea-cc2ef341e708
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9ba48dc9-f0b4-4494-8c36-4c201f29d30e
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3a4e2b4d-08b2-4f63-8299-5c38c319a03a
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a7e91359-b687-40b7-97c3-954dcb9e416d
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 41ffb4a1-9c5d-492d-be3a-bd7d27a2a4b1
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b21ef471-656c-4603-9c53-ca272b6a5680
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1f3e832f-50bb-4ce8-b8c1-bf85468f60ab:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: 'Add slide image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:8efd0c0c-fba0-499f-a93e-1b57ff148494' # Banner images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  3a4e2b4d-08b2-4f63-8299-5c38c319a03a:
    contentColumnType: text
    fieldGroup: null
    handle: intro
    instructions: ''
    name: Intro
    searchable: true
    settings:
      byteLimit: null
      charLimit: '160'
      code: ''
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9ba48dc9-f0b4-4494-8c36-4c201f29d30e:
    contentColumnType: text
    fieldGroup: null
    handle: slideTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  41ffb4a1-9c5d-492d-be3a-bd7d27a2a4b1:
    contentColumnType: string
    fieldGroup: null
    handle: buttonLink
    instructions: ''
    name: 'Button link'
    searchable: true
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  67d32d80-82f8-48c3-adea-cc2ef341e708:
    contentColumnType: text
    fieldGroup: null
    handle: category
    instructions: 'Tiny text indicating the type of content - eg if its a news item put ''news'''
    name: Category
    searchable: true
    settings:
      byteLimit: null
      charLimit: '10'
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a7e91359-b687-40b7-97c3-954dcb9e416d:
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b21ef471-656c-4603-9c53-ca272b6a5680:
    contentColumnType: string
    fieldGroup: null
    handle: position
    instructions: 'select a placement for the text box over the image'
    name: Position
    searchable: true
    settings:
      default: right
      options:
        __assoc__:
          -
            - left
            - '1'
          -
            - center
            - '1'
          -
            - right
            - '1'
          -
            - full
            - ''
          -
            - drop-left
            - '1'
          -
            - drop-right
            - '1'
    translationKeyFormat: null
    translationMethod: none
    type: rias\positionfieldtype\fields\Position
handle: slide
name: Slide
sortOrder: 1
