field: acbc0bba-242f-40cf-bdd1-a6417f6eeaa9 # Content block
fieldLayouts:
  8efae287-b2a5-469d-acc1-8b33c8126af8:
    tabs:
      -
        elements:
          -
            fieldUid: e6566bbe-eaf3-4424-9f1c-3df84eeed2ef # Video
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  e6566bbe-eaf3-4424-9f1c-3df84eeed2ef: # Video
    contentColumnType: text
    fieldGroup: null
    handle: video
    instructions: 'Add your embed code here'
    name: Video
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '6'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: video
name: Video
sortOrder: 3
