fieldLayouts:
  05729cbb-c53b-4c62-9375-aa1e0e593989:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 98b30784-0bde-4938-928a-6bf154a806a9 # Intro text
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4b6205ca-4a0d-4279-9ad6-ad8c50c87a55 # PDF Thumbnail image
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bb544c26-27bb-445d-9fb4-9c3e706a7e12 # pdfDocument
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Resource
        sortOrder: 1
handle: resourceDocument
hasTitleField: true
name: 'Resource Document'
section: 859b0ce3-be9f-4d8c-b82b-670bceeecc00 # Resources
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
