fieldLayouts:
  8015bccb-ac34-4c29-97c0-4eb2cf35fa77:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: documents
hasUrls: true
name: Documents
settings:
  path: '@assetBasePath/documents'
sortOrder: 2
type: craft\volumes\Local
url: '@assetBaseUrl/documents'
