fieldLayouts:
  4d41183a-5bd6-43d1-af6b-934d99210288:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: pdfThumbs
hasUrls: true
name: 'PDf thumbs'
settings:
  path: '@assetBasePath/images/pdfthumbs'
sortOrder: 8
type: craft\volumes\Local
url: '@assetBaseUrl/images/pdfthumbs'
