contentColumnType: text
fieldGroup: 04f271ca-91c2-45b8-a0a9-5510973cadcd # Pages
handle: altNavTitle
instructions: ''
name: 'Alternative navigation title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
