contentColumnType: text
fieldGroup: 6ddf52cb-2324-4882-b67f-2f71db18073e
handle: callbackTelephone
instructions: ''
name: 'Callback telephone'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
