contentColumnType: text
fieldGroup: 972163a3-4d75-4e5a-af88-88030b7a0689 # Global copyright
handle: charityNumber
instructions: ''
name: 'Charity number'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
