contentColumnType: string
fieldGroup: 0d3f66ab-1780-42d8-936f-e106849c2d0f # Home
handle: companyBrandLogo
instructions: 'Use this for a company brand logo to be displayed - eg over image. Transparent logos required for overlay on top of branded banner image'
name: 'Company brand logo'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:56edc24f-c24c-4013-95fb-a27456bbc077' # Brand logo
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: true
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:56edc24f-c24c-4013-95fb-a27456bbc077' # Brand logo
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
