contentColumnType: string
fieldGroup: 04f271ca-91c2-45b8-a0a9-5510973cadcd
handle: contentBlock
instructions: ''
name: 'Content block'
searchable: true
settings:
  contentTable: '{{%matrixcontent_contentblock_4}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: language
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
