contentColumnType: text
fieldGroup: 57e17ebd-5a65-4486-a175-645b52fcf8e5 # Global site info
handle: cookiepolicylinktext
instructions: ''
name: cookiePolicyLinkText
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
