contentColumnType: string
fieldGroup: f4c77426-3ec4-4532-b94d-83fff64f75c4
handle: ctaButtonColor
instructions: ''
name: 'CTA button color'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Blue
        -
          - value
          - blue
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Blue-light
        -
          - value
          - blue-light
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Gray
        -
          - value
          - gray
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Gray light'
        -
          - value
          - gray-light
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Yellow
        -
          - value
          - yellow
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
