contentColumnType: text
fieldGroup: f4c77426-3ec4-4532-b94d-83fff64f75c4
handle: ctaTextShortVersion
instructions: 'used on mobile when we want it on one line :)'
name: 'CTA text short version'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
