contentColumnType: text
fieldGroup: ac99d94b-1a00-40be-97ab-c2fce40d1100
handle: customLink
instructions: ''
name: 'Custom link'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
