contentColumnType: string
fieldGroup: 0d3f66ab-1780-42d8-936f-e106849c2d0f
handle: customBrandHeroImage
instructions: 'Use this if the company wants to upload their own brand image - it will override the original banner set and default banner'
name: 'Custom brand hero image'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:8efd0c0c-fba0-499f-a93e-1b57ff148494' # Banner images
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: true
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:8efd0c0c-fba0-499f-a93e-1b57ff148494' # Banner images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
