contentColumnType: boolean
fieldGroup: 5bd7b2c9-de07-41a0-889c-3f0fc7ef292f
handle: featureContent
instructions: 'Turn this on to make this content feature in its section'
name: 'Feature content'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
