contentColumnType: string
fieldGroup: 5bd7b2c9-de07-41a0-889c-3f0fc7ef292f
handle: featureIntroText
instructions: 'Keep this succinct - itds limited to 60 characters to facilitate SEO display'
name: 'Feature intro text'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: string
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
