contentColumnType: boolean
fieldGroup: 5bd7b2c9-de07-41a0-889c-3f0fc7ef292f
handle: featureButtonHide
instructions: 'Use this to hide the link button n the overlay'
name: 'Feature button hide'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
