contentColumnType: string
fieldGroup: 5bd7b2c9-de07-41a0-889c-3f0fc7ef292f
handle: featureImage
instructions: 'We use big screen width so we are ideally looking for 1900 x 600 px'
name: 'Feature image'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
  defaultUploadLocationSubpath: features
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
  singleUploadLocationSubpath: featured
  source: null
  sources:
    - 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
    - 'volume:e64ccb15-e61c-41a3-84f8-e9c3a375a142' # Unsplash images
    - 'volume:projectImage'
    - 'volume:8efd0c0c-fba0-499f-a93e-1b57ff148494' # Banner images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
