contentColumnType: text
fieldGroup: 934ddb53-dab9-45e3-ac3d-7d9337db8185 # Global content
handle: footerNotice
instructions: 'Text that explains any seafarer can access if they arrive here from google or mistakenly select the wrong company. *** USe placeholder [site] to substitute company site name'
name: 'Footer notice'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
