contentColumnType: text
fieldGroup: 5a3f814e-aa63-4ff9-a82b-7bf63e1eaa0a # Global tracking links
handle: includeTrackingScripts
instructions: ''
name: 'Include tracking scripts'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '8'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
