contentColumnType: text
fieldGroup: d8865574-a21c-465b-a6eb-dfaf84ae8e18 # Resource
handle: mediaUrl
instructions: 'Add the url of the media you wish to embed'
name: 'Media Url'
searchable: true
settings:
  url: ''
translationKeyFormat: null
translationMethod: none
type: wrav\oembed\fields\OembedField
