contentColumnType: text
fieldGroup: f8f993ed-1301-42d7-92b2-acb531dbe101 # News
handle: newsIntro
instructions: ''
name: 'news intro'
searchable: true
settings:
  byteLimit: null
  charLimit: '200'
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
