contentColumnType: boolean
fieldGroup: ac99d94b-1a00-40be-97ab-c2fce40d1100
handle: openInNewWindow
instructions: 'Select this to make a menu item open in a new window'
name: 'Open in new window'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Lightswitch
