contentColumnType: string
fieldGroup: d8865574-a21c-465b-a6eb-dfaf84ae8e18
handle: pdfDocument
instructions: ''
name: pdfDocument
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:8b316631-f36c-481c-8e3f-c8aab26c4c24' # Documents
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: true
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:8b316631-f36c-481c-8e3f-c8aab26c4c24' # Documents
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
