contentColumnType: text
fieldGroup: c38c46d2-bf79-4921-873b-f0ee33727fac # Staff
handle: staffJobTitle
instructions: ''
name: 'Staff job title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
