fieldLayouts:
  b9db6198-dddf-4cc3-ad21-f3d5ada72d3b:
    tabs:
      -
        elements:
          -
            fieldUid: a8866897-a11c-4d44-bbca-2997e4ab9b0c # Copyright
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1c311a44-27b4-4019-9baa-1bb97fa26364 # Charity number
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c9ad087d-6e04-43ed-af26-d691dd15c832 # Company number
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 635203ec-4f05-48bf-87b9-bae85a832e4a # Charity organisation statement
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Footer links & copyright'
        sortOrder: 1
handle: copyright
name: Copyright
sortOrder: 1
