fieldLayouts:
  8698d2ca-aabf-4f02-8e03-316641afbd58:
    tabs:
      -
        elements:
          -
            fieldUid: 85fc3b41-3642-41bd-a769-2cf9e1b27ccd # Body
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 14edf059-6ee9-43fb-83b3-2ad7ba50b48e # Image
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ec523dc0-bf00-4890-97b5-79cf4c4cf8b8 # Footer notice
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Default
        sortOrder: 1
handle: globalContent
name: 'Global Content'
