fieldLayouts:
  7369ccfc-3a2d-48e2-9ffb-73ef60ea5448:
    tabs:
      -
        elements:
          -
            fieldUid: b73a5e64-5d5e-41a7-853a-824a3024080d # Page not found
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a60f914a-c228-4c11-9e4b-56e2007fc75d # Show in dropdown
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Global site info'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 4da40367-5b18-49c8-90d8-9f0d6525d39a # Show cookie info
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d8dee4b7-c8da-42e3-aaca-bf3d942c6092 # Cookie message
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b7bc05a6-852e-4098-94e2-a61eeab3c504 # Cookie type
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 87fee2ba-71ec-49c1-8345-e86069687e5e # cookieDeny
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5f5df2da-9dc7-4641-a3c8-104b423f4ce5 # cookieDismiss
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fd3354cb-5a34-401e-9db7-c24ab958faa1 # cookiePolicyLinkText
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Global Cookie settings'
        sortOrder: 2
handle: siteInfo
name: 'Site info'
