fieldLayouts:
  eacc505c-b246-4d4b-a4eb-3db3ab541e7a:
    tabs:
      -
        elements:
          -
            fieldUid: 37e9d741-d6ef-4993-91a6-4c4750d02b84
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d60f1d78-3ea1-4eff-a47f-9fb746e6f9cf
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3ef67368-ca08-4344-8bab-3a731b6645a6
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c4c6df1b-832c-4689-8915-e0b4e6de1d7b
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 75fd46e7-4a10-4b5a-adc0-77629e5ebeef
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Social links'
        sortOrder: 1
handle: social
name: Social
